save_dir ="Data/images/train/"
dataset = ["Hello",
           "Thank you",
           "I love you",
           "Yes",
           "Please",
           "Sorry",
           "Bye",
           "No",
           "How are you",
           "I am fine",
           "Help",
           "Bathroom",
           "What",
           "Stop",
           "Friend",
           "Which",
           "Who",
           "Me",
           "You",
           "Live Long"]

